### PR TITLE
Added DIAU Network Demonsaw Router/Server.

### PR DESCRIPTION
**Pull request by inductivesoul**

### CODE REVIEW

**Comment by osteth** [comment]
I did not add it to the network yet because I attempted to connect to the
router and it was not up.

**Comment by inductivesoul** [comment]
My server, keeps getting wacky every time I get it stable. I am not sure why my router keeps breaking, give me a minute to get it back online.

--------- Original Message --------- Subject: Re: [osteth/DemonBucket] Added DIAU Network Demonsaw Router/Server. (#36)

**Comment by osteth** [comment]
I was able to connect to it a little bit ago, just let me know when you
would like me to add it and I will.  I just check them before adding them
because I get a lot of fake submissions on the site

**Comment by inductivesoul** [comment]
It's no problem, thanks for being reasonable... I have been talking on Bucket1 and decided to switch hosts, I think they're being silly. So I had my server on OVH but I am moving it to Leaseweb, after troubleshooting with Eijah and Dekka..

--------- Original Message --------- Subject: Re: [osteth/DemonBucket] Added DIAU Network Demonsaw Router/Server. (#36)

**Comment by osteth** [comment]
yeah, I tried OVH at first but they turned out to be nothing but a pain,
IMHO the price isnt worth the headache

**Comment by inductivesoul** [comment]
Go ahead and add it now I keep in mind I have one router up as IPv6 and one router up as ipv4. Diau.net

--------- Original Message --------- Subject: Re: [osteth/DemonBucket] Added DIAU Network Demonsaw Router/Server. (#36)

**Pull request merged**
